### PR TITLE
feat: add `Sort` input in `Filters`

### LINKED ISSUE #435: Add support to sort elements in ascending or descending order in blobs, blocks and transactions pages

### PR DESCRIPTION
**Pull request by xFJA**
### Checklist

- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [X] I have filled out the description and linked the related issues.

### Description
- Created `IconButtonGroup` component to be able to have a toggle between icons for the sorting types
- Added a sorting input in the `Filters` component to choose to list the items in `blocks`, `blobs` and `transactions` table views in `ascending` or `descending` order

### Related Issue

Closes #435 

### Screenshots 
image

### CODE REVIEW

**Review by luis-herasme — APPROVED** [review]

**Review by PJColombo — CHANGES_REQUESTED** [review]
I think we can simplify the design by doing something similar to the [`ThemeModeButton`](https://github.com/Blobscan/blobscan/blob/main/apps/web/src/components/ThemeModeButton.tsx): using a single icon wrapped in an IconButton that toggles between an up or down arrow icon when clicked.

I would also have the desc sort set as default

**Comment by PJColombo** [comment]
Can we also add a changeset?

**Review by PabloCastellano — APPROVED** [review]
lgtm

**Comment by xFJA** [comment]
> I think we can simplify the design by doing something similar to the [`ThemeModeButton`](https://github.com/Blobscan/blobscan/blob/main/apps/web/src/components/ThemeModeButton.tsx): using a single icon wrapped in an `IconButton` that toggles between `BarsArrowDownIcon` and `BarsArrowUpIcon` when clicked.
> 
> I would also have the desc sort set as default

Done! It seems more simple and clear now 👍

**Comment by xFJA** [comment]
> Can we also add a changeset?

The changeset script wasn't working. After fixing the config file (updating the base branch to `main`), the issue has been solved. This could be related with the recent `pnpm` update

**Review by PJColombo — APPROVED** [review]
lgtm

**Pull request merged**
