### PR TITLE
chore: fix 404 status URL

### PR DESCRIPTION
**Pull request by wangjingcun**
### Checklist

- [ ] My change requires a documentation update, and I have done it.
- [ ] I have added tests to cover my changes.
- [ ] I have filled out the description and linked the related issues.

### Description

The previous link has expired and has been replaced with the latest address.

### CODE REVIEW

**Comment by wangjingcun** [comment]
It seems that the CI error has nothing to do with this change

**Review by PabloCastellano — CHANGES_REQUESTED** [review]
@wangjingcun Well spotted! However the correct branch is 'main'. Could you replace all links to use it?

**Comment by wangjingcun** [comment]
> @wangjingcun Well spotted! However the correct branch is 'main'. Could you replace all links to use it?

I am honored to do this. I have modified it. Please review it again.

**Review by PabloCastellano — APPROVED** [review]
Nice. Thank you!

**Pull request merged**
